"""Event Sync Place

Revision ID: 6be8ea27603e
Revises: 56d1783dfa00
Create Date: 2026-06-12 04:09:59.547389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be8ea27603e'
down_revision: Union[str, None] = '56d1783dfa00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('events_name_key'), 'events', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('events_name_key'), 'events', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
