"""Event Sync Place

Revision ID: a9cac5f1bc3c
Revises: 6c413585cbdf
Create Date: 2026-06-12 04:03:59.589905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9cac5f1bc3c'
down_revision: Union[str, None] = '6c413585cbdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_time', sa.DateTime(), nullable=False))
    op.drop_column('events', 'event_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('events', 'event_time')
    # ### end Alembic commands ###
