"""add external fields

Revision ID: b1432482797e
Revises: cb49b891ec6c
Create Date: 2026-06-11 09:53:27.153709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1432482797e'
down_revision: Union[str, None] = 'cb49b891ec6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('adress', sa.String(), nullable=False))
    op.drop_column('places', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('places', 'adress')
    # ### end Alembic commands ###
